"""исправил модели wallet и user

Revision ID: 0ebac4ef28b2
Revises: a194c873fcb1
Create Date: 2025-11-16 01:24:26.612150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebac4ef28b2'
down_revision: Union[str, None] = 'a194c873fcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_wallet_id_key', 'users', type_='unique')
    op.drop_constraint('users_wallet_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'wallet_id')
    op.add_column('wallets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'user_id')
    op.add_column('users', sa.Column('wallet_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_wallet_id_fkey', 'users', 'wallets', ['wallet_id'], ['id'])
    op.create_unique_constraint('users_wallet_id_key', 'users', ['wallet_id'])
    # ### end Alembic commands ###
